"""Initial migration with Customer table

Revision ID: fc3eeec4be41
Revises:
Create Date: 2025-06-19 04:03:38.799173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3eeec4be41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('preferred_name', sa.String(length=64), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_birth_date'), ['birth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_preferred_name'), ['preferred_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_zip_code'), ['zip_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_zip_code'))
        batch_op.drop_index(batch_op.f('ix_customer_preferred_name'))
        batch_op.drop_index(batch_op.f('ix_customer_full_name'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_birth_date'))

    op.drop_table('customer')
    # ### end Alembic commands ###
